version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: linex-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - linex-network

volumes:
  redis_data:
    driver: local

networks:
  linex-network:
    driver: bridge